---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereq
    - role: download
    # - role: raspberrypi

- hosts: storage
  become: yes
  roles:
    - role: longhorn
    - role: openebs

- hosts: openebs
  become: yes
  roles:
    - role: openebs

- hosts: master
  become: yes
  roles:
    - role: k3s/master

- hosts: compute:storage
  become: yes
  roles:
    - role: k3s/node
