---
- name: Verify Huge Page support
  shell: grep HugePages_Total /proc/meminfo
  register: huge_pages_status

- name: Display Huge Page support status
  debug:
    msg: "{{ huge_pages_status.stdout }}"

- name: Adjust Huge Page count if necessary
  shell: echo 1024 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
  when: huge_pages_status.stdout_lines[0].split(":")[1] < 1024

- name: Persist Huge Page count across reboots
  shell: echo vm.nr_hugepages = 1024 | sudo tee -a /etc/sysctl.conf
  when: huge_pages_status.stdout_lines[0].split(":")[1] < 1024

- name: Restart kubelet to apply Huge Page changes
  shell: systemctl restart kubelet
  when: huge_pages_status.stdout_lines[0].split(":")[1] < 1024
